server:
  port: 8080

spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  datasource:
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/kakalog?useUnicode=true&characterEncoding=utf-8&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
      username: root
      password: admin
      #配置用于监控统计拦截的filters（去除后监控界面的SQL无法统计），wall 用于防火墙
      filters: stat,wall,log4j,config
      #最大连接数
      max-active: 100
      #初始化大小
      initial-size: 10
      #获取链接等待超时时间
      max-wait: 60000
      #最小连接数
      min-idle: 1
      #检测间隔时间（检测需要关闭的空闲连接，单位毫秒）
      time-between-connect-error-millis: 60000
      #链接在链接池中最小生存时间（毫秒）
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 50
      max-pool-prepared-statement-per-connection-size: 20



mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl